### ISSUE TITLE
How do I use this code using LinRS test tool?

### ISSUE THREAD

**Issue by diogo24m** [niro16/LinMot_Drives_using_Python3#1]
When I start the LinRS test tool, t I can't run this code because the serial port is busy. 
When running the code without test tool , the code prints "incomplete telegram".

Am I missing something here?

(I'm using C1250 drive)

**Comment by thuggish16** [comment]
In order for the LinRS test tool to work, you have to select the same COM port as your code. For example, COM7 in python should correspond to COM7 in LinRS test tool. You can start by testing the telegrams on LinRS test tool, then go over to python. If you manage to get it to work in LinRS test tool, then python should work as well.
